services:
  - type: web
    name: csv-analytics-dashboard
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install --only-binary=all -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12